import:
  - ~/.config/alacritty/themes/onedark.yml

window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: full
  startup_mode: Maximized
  dynamic_title: true

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular

  bold:
    family: FiraCode Nerd Font Mono
    style: Bold

  italic:
    family: Hack Nerd Font Mono
    style: Italic

  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  size: 14.0

cursor:
  style: Beam
  vi_mode_style: Block
  unfocused_hollow: true

alt_send_esc: false

hints:
  enabled:
    - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: Command
        binding:
          key: U
          mods: Control|Shift

key_bindings:
  - { key: K, mods: Command, mode: ~Vi, chars: "\x0c" }
  - { key: Slash, mods: Control, mode: ~Vi, chars: "\x1f" }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: K, mods: Command, action: ClearHistory }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: C, mods: Command, mode: Vi, action: ClearSelection }
  - { key: H, mods: Command, action: Hide }
  - { key: M, mods: Command, action: Minimize }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: F, mods: Command|Control, action: ToggleFullscreen }
  - { key: F, mods: Command, action: SearchForward }
  - { key: B, mods: Command, action: SearchBackward }
  - { key: Left, mods: Alt, chars: "\x1bb" }
  - { key: Right, mods: Alt, chars: "\x1bf" }
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor }
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor }
  - { key: Back, mods: Command, chars: "\x15" }
