#!/bin/sh

if [ -f "$HOME/.Brewfile" ]; then
  echo "Updating homebrew bundle..."
  brew bundle --global
fi

# install Oh My ZSH
if [ ! -d "$HOME"/.oh-my-zsh ]; then
  echo "installing oh-my-zsh..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# Install autosuggestions
if [ ! -d "$HOME"/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
  echo "installing zsh-autosuggestions..."
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

# Install syntax highlighting
if [ ! -d "$HOME"/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]; then
  echo "installing zsh-syntax-highlighting..."
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

# Upgrade or install vim-plug
if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  nvim -E -s +PlugUpgrade +qa
else
  echo "installing vim-plug..."
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Update vim plugins
echo "updating vim plug plugins..."
nvim +PlugUpdate +PlugClean! +qa

# Clear screen
reset -Q
