tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "ysdexlic/formulae"

brew "git"
brew "go"
brew "neovim"
brew "node"
brew "python@3.9"
brew "rust"
brew "starship"
brew "tmux"
brew "ysdexlic/formulae/dot"

cask "alacritty"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
