tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "ysdexlic/formulae"

brew "bat"
brew "gh"
brew "git"
brew "neofetch"
brew "neovim"
brew "python@3.9"
brew "the_silver_searcher"
brew "starship"
brew "tmux"
brew "ysdexlic/formulae/dot"

cask "blackhole-2ch"
cask "font-hack-nerd-font"
