format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$golang\
$kotlin\
$nodejs\
$python\
$rust\
$swift\
$terraform\
$kubernetes\
$memory_usage\
$openstack\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""
