colors:
  primary:
    background: "#282c34"
    foreground: "#abb1bf"

  normal:
    black: '#000000'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#e5c07b'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#abb2bf'

  bright:
    black: '#4b5263'
    red: '#be5046'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#3e4452'
